"""database table creation

Revision ID: 17fe7bb29450
Revises: 
Create Date: 2025-01-08 22:05:41.114471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17fe7bb29450'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HEALTH_CATEGORY',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('HEALTH_INFLUENCER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('twitter_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('twitter_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('trend', sa.Enum('UP', 'DOWN', 'STABLE', name='trendenum'), nullable=False),
    sa.Column('trust_score_avg', sa.Float(), nullable=False),
    sa.Column('number_verified_claims', sa.Integer(), nullable=False),
    sa.Column('estimated_annual_earnings', sa.Float(), nullable=False),
    sa.Column('primary_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_category_id'], ['HEALTH_CATEGORY.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('twitter_url')
    )
    op.create_index(op.f('ix_HEALTH_INFLUENCER_twitter_nickname'), 'HEALTH_INFLUENCER', ['twitter_nickname'], unique=True)
    op.create_table('HEALTH_CLAIM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_influencer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['health_influencer_id'], ['HEALTH_INFLUENCER.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CLAIM_HEALTH_CATEGORY',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['HEALTH_CATEGORY.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['HEALTH_CLAIM.id'], ),
    sa.PrimaryKeyConstraint('claim_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CLAIM_HEALTH_CATEGORY')
    op.drop_table('HEALTH_CLAIM')
    op.drop_index(op.f('ix_HEALTH_INFLUENCER_twitter_nickname'), table_name='HEALTH_INFLUENCER')
    op.drop_table('HEALTH_INFLUENCER')
    op.drop_table('HEALTH_CATEGORY')
    # ### end Alembic commands ###
